### ISSUE TITLE
[São Paulo/SP] Richard Manzoli

### ISSUE THREAD

**Issue by manzolirch** [react-brasil/me-contrata#15]
## Nome completo

Richard Manzoli

## Localidade

São Paulo - SP

## Apresentação

Trabalho a 2 anos como desenvolvedor e a 1 ano com foco em Front-end, atualmente uso e foco meus estudos em JavaScript (Vanilla JS, ReactJS), CSS (SASS).

## Outras Informações

Procuro oportunidade para trabalhar como Front-end, Junior ou Pleno, para trabalhar com VanillaJS, React ou React-Native.

## Especialidades

- JavaScript
- React
- CSS
- SASS
- API
- Git

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [x] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/richard-manzoli/

## Site

https://github.com/manzolirch/curriculo

**Comment by jgcmarins** [comment]
Dá uma olhada nas vagas da Entria: https://github.com/entria/jobs.
Pode me procurar no Slack do React Brasil também.
