### ISSUE TITLE
[São Paulo/SP] Lucas Henrique M Dourado

### ISSUE THREAD

**Issue by LuucasMachado** [react-brasil/me-contrata#17]
## Nome completo

Lucas Henrique Machado Dourado

## Localidade

São Paulo - SP

## Apresentação

Desenvolvedor front end com atuação com diversos framework e bibliotecas javascript, gosto de participar da concepção e planejamento e estou sempre aberto a novas ideias e conhecimentos.

## Especialidades

- JavaScript
- React
- Redux Saga
- Angular
- Jquery
- BEMCSS
- ITCSS
- Bootstrap
- Processos ágeis
- Webpack
- Bower
- Npm
- Git
- Jest
- Ruby
- Rails

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/lucas-henrique-machado-dourado-77698317/

## Site

https://github.com/LuucasMachado
+5511981654157

**Comment by sibelius** [comment]
entra no slack do react brasil http://react.now.sh e me dá um ping
