### ISSUE TITLE
[Curitiba/PR] Rodrigo Muniz

### ISSUE THREAD

**Issue by muniz95** [react-brasil/me-contrata#2]
## Nome completo

Rodrigo Muniz

## Localidade

Curitiba - PR

## Apresentação

Atuo desde 2011 com desenvolvimento web, tendo passado por diversas empresas e convivido em ambientes completamente distintos. Já tive contato com diversas tecnologias e padrões diferentes, e isso ajudou a aceitar e compreender coisas novas com mais facilidade.

Sou curioso por natureza; estou sempre me aventurando em áreas diferentes, tanto em programação quanto em outros meios.

Meu stack preferido hoje consiste em: Angular/React, PostgreSQL, .NET Core, Ruby e Node, com os quais trabalho atualmente. Gosto de entender o todo de tudo, por isso tenho conhecimentos também, ainda que menos abrangentes, em testes, análise e modelagem de sistemas, DevOps, UX e metodologias ágeis.

## Outras Informações

Estou em busca de freelas em meio período e trabalho remoto, contratação PJ.

## Especialidades

- JavaScript
- React
- Dart
- Flutter
- Angular
- AngularJS
- Redux
- Ruby / Rails
- Node

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/muniz95/

## Site

https://muniz95.github.io

**Comment by welingtonsampaio** [comment]
Olá @muniz95 tudo bom?! Estamos com uma vaga para desenvolvedor React aberto aqui na empresa, teria enteresse em participar?
Link da vaga: frontendbr/vagas#1722

**Comment by muniz95** [comment]
Sim
