### ISSUE TITLE
[GOIÂNIA-GO] Murilo Medeiros

### ISSUE THREAD

**Issue by miticous** [react-brasil/me-contrata#29]
## Nome completo

Murilo Andrade Medeiros

## Localidade

Goiânia-GO

## Apresentação

Tenho bastante facilidade no desenvolvimento de UI uma vez que tenho uma base muito boa do desenvolvimento com HTML, CSS e Bootstrap. Crio por padrão layouts flexíveis, uso as propriedades **_width_** e _**height**_ só em casos extremos (para React Native)... Embora eu tenha experiências fullstack o meu forte é front-end.

## Especialidades

- JavaScript
- React
- React Native
- GraphQL
- Redux
- Jest

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/mam17/

**Comment by itspauloroberto** [comment]
http://www.geekhunter.com.br/
