### ISSUE TITLE
[São Paulo/SP] Gabriela Freitas

### ISSUE THREAD

**Issue by freitasgst** [react-brasil/me-contrata#3]
## Nome completo

Gabriela de Sá Teles Freitas

## Localidade

São Paulo / SP

## Apresentação

Comecei a programar desenvolvendo jogos, em 2010. Depois de graduar na faculdade, em 2013, me especializei em animação 2D e venho trabalhando com isso desde então. Quero reingressar para a área de tecnologia e voltei a estudar programação com foco em front-end no início de 2018. 

## Outras Informações

- Disponibilidade para trabalho integral. 

## Especialidades

- JavaScript
- React
- React Native

## Tempo de experiência na área

- [ ] < 1 ano
- [x] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

Sem LinkedIn

## Site

https://github.com/freitasgst

**Comment by danielGalvao** [comment]
Boa @freitasgst! Mas acho válido colocar no tempo que você já trabalhou com programação/animação
Vou mudar para "Tempo que já trabalhou com TI"

**Comment by gask** [comment]
Boa tarde @freitasgst ! Temos uma vaga aqui na **Mobicity** para Desenvolvedora Web Jr. que acreditamos que te interessaria, se tiver interesse acessa o link: https://www.catho.com.br/vagas/compartilhada/13659538
ou entra em contato com a gente enviando seu CV para o contato@mobicity.com.br

**Comment by jeanlucaslima** [comment]
@freitasgst qual melhor contato contigo? Ali diz só "Sem Linkedin"

**Comment by freitasgst** [comment]
Olá @jeanlucaslima ! Meu email é freitasgst@gmail.com, costumo responder rapidinho por aí (: Até!
