### ISSUE TITLE
a

### ISSUE THREAD

**Issue by h4yha** [react-brasil/me-contrata#31]

**Comment by bluuesz** [comment]
> ## Nome completo
> ......
> 
> ## Localidade
> Campina Grande - PB
> 
> ## Apresentação
> Full stack developer, entusiasta pela stack js e apaixonado por segurança da informação
> 
> ## Especialidades
> * Reactjs
> * JavaScript
> * VueJS
> * Nodejs
> 
> ## Tempo de experiência em TI (Não necessáriamente Front-end/React)
> * [x]  < 1 ano
> * [ ]  > 1 ano
> * [ ]  > 2 anos
> * [ ]  > 5 anos
> 
> ## Nível
> * [x]  Estágio
> * [x]  Júnior
> * [ ]  Pleno
> * [ ]  Sênior
> 
> ## Tipo de contratação
> * [x]  PJ
> * [x]  CLT
> * [x]  Freela
> 
> ## Tipo de trabalho
> * [x]  Remoto - Parcial
> * [x]  Remoto - Total
> * [x]  Alocado
