### ISSUE TITLE
 [Rio de Janeiro/RJ] Rafaela Cutalo Moreira

### ISSUE THREAD

**Issue by RafaelaCutalo** [react-brasil/me-contrata#38]
## Nome completo

Rafaela Cutalo Moreira

## Localidade

 Rio de Janeiro, RJ

## Apresentação

Durante mais de 6 anos atuei na área administrativa especializada em logística. Mas seguindo a necessidade de melhoria contínua e um mindset de crescimento comecei um novo desafio para amadurecer tanto profissionalmente como pessoalmente.

Hoje atuo como desenvolvedora web, formei em Análise e desenvolvimento de sistemas e tenho me especializado em projetos digitais com foco no usuário.
 

## Outras Informações

Em 2019 concluí o curso de JavaScript moderno da Caelum e atualmente estou estudando o React.JS.
Estou a procura de vagas para React.JS Júnior e tenho disponibilidade para viagens e mudança para outros estados.

## Especialidades

- JavaScript
- React
- Bootstrap
- JQuery
- HTML
- CSS
- SASS

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [x] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/rafaela-cutalo-83292ba5/

**Comment by sibelius** [comment]
Tem interesse de fazer o challenge da @entria https://entria.contrata.vc/ ?

me manda DM no slack se quiser mais detalhes da vaga

**Comment by RafaelaCutalo** [comment]
Sim


Em qui, 30 de abr de 2020 16:05, stale[bot] <notifications@github.com>
escreveu:

**Comment by yuritoledo** [comment]
Olá!

Dê uma olhada nessa vaga que tenho aqui na empresa e veja se te interessa :)
https://github.com/frontendbr/vagas/issues/3151
