### ISSUE TITLE
[Dourados/MS] Felipe Nascimento Santos

### ISSUE THREAD

**Issue by santosfelip** [react-brasil/me-contrata#41]
## Nome completo

Felipe Nascimento Santos

## Localidade

Dourados/ms

## Apresentação

Sou mais um apaixonado por tecnologia, programação, pesquisa e inovação. Vencedor da Maratona Maker Intel Brasil/ 2016. Melhor do Centro-Oeste na copa Rio de Algoritmo/ 2016. Primeiro lugar na Olímpiada Brasileira de Robótica na modalidade teórica/ 2016. Desenvolveu e apresentou vários projetos como: Software de Reconhecimento da Qualidade da Carne Bovina por foto, (Walter Clean) Garrafa que limpa e esteriliza a água. 

## Especialidades

- JavaScript
- React
- Redux
- HTML
- CSS
- Bootstrap
- MongoDB
- Java
- Spring Boot
- C, C++
- MySQL

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [x] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/santosfelip

**Comment by jgcmarins** [comment]
@santosfelip dá uma olhada nas vagas da @FotonTech: https://github.com/FotonTech/join
Qualquer coisa me procura no Slack do React Brasil: https://react.now.sh

**Comment by gabrielferreiraa** [comment]
@santosfelip olha ai a oportunidade ;)
