### ISSUE TITLE
[Fortaleza/CE] Carlos Eugênio Costa Barros Junior

### ISSUE THREAD

**Issue by eugeniobarrosjr** [react-brasil/me-contrata#43]
## Nome completo

Carlos Eugênio Costa Barros Junior

## Localidade

Fortaleza / CE

## Apresentação

Desenvolvedor FrontEnd / Mobile, com quase 3+ anos de experiência profissional, onde trabalhei em projetos notáveis e desafiadores ao longo da minha trajetória.

## Outras Informações

Disponível pata início imediato.
Remoto ou Alocado

## Especialidades

- HTML5 / CSS3
- ES6+,  ReactJs, Redux, Redux Saga
- Ionic 3, React Native, Flutter
- Firebase 
- Google API

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [x] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/eugeniobarrosjr

**Comment by jonathangaldino** [comment]
Adiciona seu nome no título do issue :D

**Comment by eugeniobarrosjr** [comment]
> Adiciona seu nome no título do issue :D

Obrigado @jonathangaldino ,

**Comment by eugeniobarrosjr** [comment]
Fui contratado. :+1:
