### ISSUE TITLE
[Rio Claro/SP] Angelo Rogério Rubin

### ISSUE THREAD

**Issue by angelorubin** [react-brasil/me-contrata#5]
## Nome completo

Angelo Rogério Rubin

## Localidade

Rio Claro - SP

## Apresentação

Objetivos
Desenvolvedor Frontend
Educação
Segundo Grau Completo
2008 | Gestão de Sistemas de Informações

Experiências
•	Desenvolvedor Front-End Freelancer ( + 2 anos)
•	Desenvolvedor Front-End | 2012
E-mix (campinas) | www.emix.com.br

Tecnologias/Ferramentas

•	HTML,
•	CSS (Less , Sass básico, Styled Components, BEM),
•	Javascript,
•	Git,
•	GitHub, Bitbucket, GitLab,
•	jQuery, 
•	VueJS,
•	ReactJS,
•	GraphQL (Básico), 
•	Laravel (Básico), 
•	MySQL, 
•	Node.js (Básico)
•	Express.js (Básico)
•	MongoDB (Básico)
•	Desenvolvimento e montagem de layouts fluídos e responsivos ( Bootstrap, Bulma, etc ),
•	Levantamento de requisitos, 
•	Modelagem de banco de dados Relacional e NoSQL,
•	Webpack
•	Fireworks, 
•	MySQL WorkBeanch, 

## Outras Informações

Disponibilidade trabalho remoto

## Especialidades
JavaScript
React

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [x] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [ ] Alocado

## Contato

https://linkedin.com/in/angelorubin

## Site

https://github.com/angelorubin

**Comment by angelorubin** [comment]
SIM.

**Comment by yuritoledo** [comment]
https://github.com/frontendbr/vagas/issues/1948
:)

**Comment by angelorubin** [comment]
Valeu !

Em qui, 30 de mai de 2019 às 23:13, Yuri Toledo <notifications@github.com>
escreveu:

**Comment by angelorubin** [comment]
Estou.

**Comment by angelorubin** [comment]
Estou disponível.

**Comment by angelorubin** [comment]
Estou disponível.

**Comment by angelorubin** [comment]
Estou disponível.

**Comment by angelorubin** [comment]
Sim.

**Comment by angelorubin** [comment]
Estou disponivel.

**Comment by angelorubin** [comment]
Estou disponível.
