### ISSUE TITLE
[São Paulo/SP] Enieber Cunha

### ISSUE THREAD

**Issue by enieber** [react-brasil/me-contrata#52]
## Nome completo

Enieber Cunha da Silva

## Localidade

São Paulo /SP

## Apresentação

Sou desenvolvedor js com foco em mobile. Já trabalhei desde mobile a api em nodejs. Tenho experiência em configurar aplicação em docker para desenvolvimento e aws para produção. Tenho experiência com projetos open source.

## Outras Informações

Tenho curso técnico em informática, aprendo muita coisa sem professor e gosto de compartilhar meus conhecimentos com palestras, cursos e respondendo dúvidas na comunidade.

## Especialidades

- JavaScript
- React
- React Native
- Redux
- Jest

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [x] 5 anos (comecei em 2015)

## Nível

 - [x] Pleno

## Tipo de contratação

- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/enieber

## Site

https://enieber.github.io

**Comment by renanmav** [comment]
Oi Enieber. 

A gente tá com uma vaga aberta aqui na Foton pra fullstack. Aceitamos remoto. Pra entrar você precisa fazer o [nosso challenge](https://github.com/fotontech/join).

Se você ficou interessado e quer tentar, procura a gente (eu, @jgcmarins ou @jaburx) no [slack do React Brasil](https://react-brasil-slack.herokuapp.com/) e entra no canal #challenge-foton que nós te ajudamos no aprendizado.

**Comment by enieber** [comment]
valew @renanmav já comecei a fazer o challenge

**Comment by yuritoledo** [comment]
Olá!

Dê uma olhada nessa vaga que tenho aqui na empresa e veja se te interessa :)
https://github.com/frontendbr/vagas/issues/3151
