### ISSUE TITLE
 [São Paulo/SP] Daniela Duarte

### ISSUE THREAD

**Issue by daniduarteng** [react-brasil/me-contrata#54]
## Nome completo

Daniela Duarte

## Localidade

São Paulo

## Apresentação

Desenvolvedora Front-End, Técnica em Informática e Engenheira da Computação.

Apaixonada por tecnologia e empreendedorismo, apoia o desenvolvimento de mais mulheres na área de tecnologia, por isso escreve no seu blog (www.danieladuarte.com.br) sobre tecnologia, experiências e aprendizados, a fim de inspirar e orientar cada vez mais, mulheres que estão ou querem entrar no mundo da computação.

Possui experiência nas áreas de tecnologia, administração e marketing desde startups à multinacionais como Santa Marina, CBB Web (Medcel), Saint-Gobain e Kestraa.

Teve seu TCC (Cartão Virtual Biométrico) patenteado e selecionado para o programa de mentoria de startups da Escola de Negócios do Sebrae.

Selecionada entre 2500 inscrições para ser uma das 100 mulheres empreendedoras a participar do programa de liderança feminina da Google o Womenwill.

## Outras Informações

Trabalho remotamente

## Educação:

UDACITY Brasil
Nanodegree Desenvolvedor React
2018-2019

UNIBTA - Centro Universitário
Bacharel em Engenharia da Computação
2013-2017

ETEC Jaraguá
Técnico em informático com ênfase em programação
2012-2013

Codecademy
Learn HTML & CSS
2017

Codecademy
Learn Responsive Design
2017

TIEXAMES
Fundamentos em Gerenciamento de Serviços de TI com base na ITIL Foundation (V3 - ed. 2011)
2015

## Especialidades

- JavaScript
- React
- React Native
- Redux
- Jest
- Enzyme
- HTML/HTML5
- CSS/CSS3/ Material UI, Stylus e CSS in JS 
- Formik
- Design Responsivo
- Usabilidade
- Mobile First
- Git/GitHub

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/danieladuarteng/

## Site

https://www.danieladuarte.com.br/

**Comment by jgcmarins** [comment]
@danieladuarteng dá uma olhada nas vagas da @sallve
- [sallve/jobs](https://github.com/sallve/jobs)
- [react-brasil/vagas](https://github.com/react-brasil/vagas/issues/1009)

**Comment by daniduarteng** [comment]
Estou atualmente num projeto, por isso no momento estou indisponível, obrigada todos

**Comment by daniduarteng** [comment]
@jgcmarins obrigada, mas hoje meu foco é só frontend mesmo. Agradeço
