### ISSUE TITLE
[Sao Paulo/SP] Rafael Bonifacio

### ISSUE THREAD

**Issue by rsboni** [react-brasil/me-contrata#55]
## Nome completo

Rafael Bonifácio

## Localidade

São Paulo/SP

## Apresentação

Há muito tempo mexo com programação mas agora estou me dedicando mais integralmente a trabalhar somente na área em tempo integral. Cursei física na USP e música na UNESP, já trabalhei em orquestras, e atualmente trabalho como freelancer frontend e paralelamente com captação e edição de som direto pra cinema.

## Outras Informações

Disponibilidade total, ainda mais neste tempo de quarentena!

## Especialidades

- JavaScript
- React
- React Native
- Redux
- HTML/CSS

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/rsbonifacio

## Site

https://github.com/rsboni

**Comment by yuritoledo** [comment]
Olá!

Dê uma olhada nessa vaga que tenho aqui na empresa e veja se te interessa :)
https://github.com/frontendbr/vagas/issues/3151
