### ISSUE TITLE
[Porto Alegre/RS] Thayná Minuzzo

### ISSUE THREAD

**Issue by TMinuzzo** [react-brasil/me-contrata#59]
## Nome completo

Thayná Minuzzo

## Localidade

 Porto Alegre/RS 

## Apresentação

I have been in the software development area for three years as a fullstack developer, and always seek to participate in projects or events related to technology and the encouragement of women. 
I'm currently a graduate student in Computer Engineering at Universidade Federal do Rio Grande do Sul (UFRGS). I worked as a front and back-end developer of an application for high-resolution video conference between multi teleconference rooms for almost two years, and after that I worked at HP Brazil as software developer acting on a global team.

## Outras Informações

Searching for a remote part-time job, interested in solving problems and help other people! 😊

## Especialidades

- JavaScript/ES6
- React
- Redux
- Node.js
- Rest API
- HTML/CSS
- Java
- Spring boot
- C++
- Python
- Django
- Ruby on Rails
- AWS/Azure

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/thayna-minuzzo-69b7aab3/

## Site

https://github.com/TMinuzzo

**Comment by jgcmarins** [comment]
Hello @TMinuzzo,
We have few open positions at @FotonTech. For more details, check https://github.com/FotonTech/join.
You can also reach me out at React Brasil's slack channel https://react.now.sh.
We have a public channel where we give mentorship and help candidates to complete their challenges.
You can also send me a DM and I can give you more details about @FotonTech's projects and culture.
By the way, we're located at Florianópolis, but we're running 100% remote.
