### ISSUE TITLE
[São Paulo/SP] Eldad Hauzman

### ISSUE THREAD

**Issue by ehauzman** [react-brasil/me-contrata#6]
## Nome completo

Eldad Hauzman

## Localidade

São Paulo / SP

## Apresentação

Construí uma carreira de vários anos em TI, tendo dedicado a parte de gestão, consultoria e auditoria. Há algum tempo decidi empreender e agora busco novos rumos criando novas ferramentas e aprendendo novas tecnologias.

## Outras Informações

Venho estudando através de cursos na Udemy: JavaScript, React, Node.js, Express, MongoDB, APIs, entre outros. Tenho disponibilidade integral.

## Especialidades

- JavaScript
- React
- Redux
- Node.js
- Express
- MongoDB
- AWS

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/ehauzman/

**Comment by lucasbento** [comment]
@ehauzman: pode especificar o tipo de contratação, por gentileza?

**Comment by welingtonsampaio** [comment]
Olá @ehauzman tudo bom?! Estamos com uma vaga para desenvolvedor React aberto aqui na empresa, teria enteresse em participar?
Link da vaga: https://github.com/frontendbr/vagas/issues/1722
