### ISSUE TITLE
[Tupã/SP] Felipe Bruvers

### ISSUE THREAD

**Issue by bruversFelipe** [react-brasil/me-contrata#61]
## Nome completo
Felipe Fernandes Bruvers

## Localidade

Tupã / SP

## Apresentação

Desenvolvedor React JS desde setembro de 2017 e trabalhando com html 5 e css 3 desde 2015

## Outras Informações

Disponível para mudança

## Especialidades

- JavaScript
- React
- HTML5
- CSS3

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/felipe-bruvers-9b2442b3/

**Comment by marcelodl** [comment]
Boa noite Felipe, tudo bem? Tens interesse em participar de um projeto com escopo inicial de 3 meses, mas com possibilidade de efetivação após esse periodo? Se sim, me manda uma mensagem.

**Comment by bruversFelipe** [comment]
@marcelodl Bom dia! Tenho preferência em algo mais duradouro no momento, a não ser que o projeto não seja necessário mais que duas horas diárias de desenvolvimento

**Comment by marcelodl** [comment]
Oi Felipe! Acho que podemos conversar sim. Me manda uma msg no meu linkedin em https://www.linkedin.com/in/marcelodinizlima/
