### ISSUE TITLE
 [Paranavaí/PR] Maria de Fátima Ferreira

### ISSUE THREAD

**Issue by MariaFF** [react-brasil/me-contrata#62]
## Nome completo

Maria de Fátima Ferreira

## Localidade

Paranavaí - PR

## Apresentação

Sou dev mobile React Native, aproximadamente 2 anos de experiência com essa tecnologia. Durante esse período trabalhei na migração de um app Android já em produção para React Native. Para isso além da tecnologia citada utilizei, graphQl, socket.io, redux, async storage, hooks e outros. Também participei de algumas tarefas em uma api php. 

## Outras Informações

Atualmente estou fazendo o GoStack Bootcamp da Rocketseat, onde é abordado toda a stack js.
Tenho interesse em vagas mobile, porém considero também aprender novas plataformas, sendo backend e web, além de outras linguagens.

## Especialidades

- JavaScript
- React Native
- Hooks
- Rest
- GraphQL
- Socket.io
- Redux
- Async storage
- React
- Node
- Android

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/maria-de-f%C3%A1tima-ferreira-b59aa0104/

**Comment by yuritoledo** [comment]
Olá!

Dê uma olhada nessa vaga que tenho aqui na empresa e veja se te interessa :)
https://github.com/frontendbr/vagas/issues/3151
