### ISSUE TITLE
[Caxias do Sul/RS] Breno Fiorese

### ISSUE THREAD

**Issue by brenowss** [react-brasil/me-contrata#65]
## Nome completo

Breno Carra Fiorese

## Localidade

Antônio Prado / Rio Grande do Sul

## Apresentação

Sou desenvolvedor front-end há mais de 1 ano, e conheci o ecossistema React há aproximadamente 6 meses. Sou apaixonado em criar coisas do zero, concretizar algo a partir de uma ideia.
Tenho formação de Técnico em Informática, e foi nesse curso que fui introduzido a programação, e desde a primeira aula, nunca mais parei de desenvolver algo todos os dias.
Trabalhei por quase um ano em uma empresa de software como desenvolvedor e suporte técnico, e lá aprendi muito sobre trabalho em equipe e como lidar com clientes dos mais diversos estilos.

## Outras Informações

Atualmente moro em Antônio Prado, que é uma cidade próxima a Caxias do Sul, tenho disponibilidade de me locomover até lá.

## Especialidades
- JavaScript
- React
- React Native
- HTML
- CSS
- PHP
- UI/UX

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/breno-fiorese/

## Site

https://brenofiorese.netlify.app/

**Comment by jgcmarins** [comment]
Dá uma olhada nas vagas da @FotonTech: https://github.com/FotonTech/join
Qualquer dúvida pode procurar a gente no Slack do React Brasil no channel `#challenge-foton`
