### ISSUE TITLE
[Tupã/SP] Vitor Tarnoschi

### ISSUE THREAD

**Issue by vTarnoschi** [react-brasil/me-contrata#67]
## Nome completo

Vitor Tarnoschi

## Localidade

Tupã - SP

## Apresentação

Desenvolvedor ReactJS utilizando Redux, Redux Saga e API em .NET Core e algumas aplicações com NODE JS utilizando Express e MongoDb.

## Outras Informações

Disponível para mudança

## Especialidades
 - JavaScript
 - React
 - Redux
 - Redux Saga
 - NodeJS

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

**Comment by keviocastro** [comment]
@vTarnoschi sou de Goiânia e estou com 4 vagas para trabalho home office. Contratação imediata. Podemos fazer uma call pra eu te explicar melhor? Me envie um email por favor keviocastro@gmail.com ou também pode me ligar 62 996026753

**Comment by marcelodl** [comment]
Oi Victor, tudo bem? Estou uma vaga para dev react aqui na empresa. Entra em contato comigo no linkedin pra eu te explicar melhor e ver se você tem interesse. O link é https://www.linkedin.com/in/marcelodinizlima/. Abraço!
