### ISSUE TITLE
[Duque de Caxias/RJ] Marcos Silva de Souza

### ISSUE THREAD

**Issue by marcossouzadotdev** [react-brasil/me-contrata#68]
## Nome completo

Marcos Silva de Souza

## Localidade

Duque de Caxias - RJ

## Apresentação

Sou estudante de programação desde Abril de 2018, focando em web a partir do fim de 2018. No começo de 2019 comecei a estudar sobre React. 

Sempre fui autodidata, costumo ler bastante livros, documentações, artigos e discussões em redes sociais (como reddit, stackoverflow etc), também, por necessidade, costumo ir pra tecnologias novas com bastante frequência. 

Sempre estudei sem recursos, e nesse mês (Agosto de 2020) fiz inscrição em Bacharelado em Matemática, e pretendo investir muito na carreira e desenvolvimento pessoal assim que conseguir um emprego fixo.

## Outras Informações

Disponível para qualquer horário e possibilidade para mudança

## Especialidades

- JavaScript
- React
- Redux
- Nextjs
- Python
- Django
- Wagtail
- SQL
- Linux
- Git

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [x] > 2 anos

## Nível

- [x] Estágio
- [x] Júnior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela
- [x] Estágio

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/flakesrc

## Site

marcossouza.dev (em construção)
https://linktr.ee/flakesrc

**Comment by jgcmarins** [comment]
@flakesrc dá uma olhada nas vagas da @FotonTech: https://github.com/FotonTech/join
Qualquer dúvida pode procurar a gente no Slack do React Brasil: https://react.now.sh, no channel `#foton-challenge`

**Comment by marcossouzadotdev** [comment]
@jgcmarins  não aparece o canal `#foton-challenge` aqui pra mim. Tirando que pelos requisitos parece vagas pra pl/senior, e eu nem entrei no mercado ainda praticamente.

**Comment by jgcmarins** [comment]
Correção: `#challenge-foton`

**Comment by marcossouzadotdev** [comment]
@jgcmarins  não tem nada do tipo. https://i.imgur.com/EYUsJ0q.png

**Comment by jgcmarins** [comment]
Te chamei lá

**Comment by marcosh72** [comment]
@flakesrc opa! caso ainda esteja disponível, dá uma olhada na vaga que a Kartado abriu! https://www.kartado.com.br/vagas/

**Comment by keviocastro** [comment]
@flakesrc sou de Goiânia e estou com 4 vagas para trabalho home office. Contratação imediata. Podemos fazer uma call pra eu te explicar melhor? Me envie um email por favor keviocastro@gmail.com ou também pode me ligar 62 996026753
