### ISSUE TITLE
[São Luís/MA] Cleberson Junior

### ISSUE THREAD

**Issue by cleberson-dev** [react-brasil/me-contrata#69]
## Nome completo

Cleberson Ferreira Rodrigues Junior

## Localidade

São Luís - MA

## Apresentação

Amo informática desde que entendo por gente. Vim de uma família que compartilha das mesmas preferências (um pai que programava em Delphi), o que tornou as coisas pouco mais fáceis para mim. Sempre que possível, realizava manutenções em computadores de habitantes do meu interior e dava assistência junto com meu pai na prefeitura. 
Atualmente, já no meu 8º período de de Engenharia da Computação, estou pavimentando meu caminho de ser um desenvolvedor web, principalmente front end. 📱 
Comecei a gostar da Web escrevendo duas aplicações full-stack com PHP e MySQL (bom e velho XAMPP ajudando) e comecei a amar cada vez mais estudando e entendendo como funciona, testando com Python (Django e Flask), até parando e focando em uma tecnologia específica, sendo hoje Javascript. O ecossistema é grande, o que me mostrou e me expôs a muitas outras ferramentas e tecnologias facilitando e acelerando meu trabalho principal de construir interfaces interativas, responsivas, performáticas e usáveis. Por isso hoje, sou desenvolvedor front-end React.js, mesmo conhecendo e usando outras tecnologias similares como Vue.js e Angular. 
React.js é minha especialidade, e meu bebê ^-^ :heart:

## Outras Informações

Como dito, sou estudante de Engenharia da Computação, já no 8º período. Porém estudo a noite, o que me dá o resto do dia livre. Resido no Maranhão, o que me faz candidatar a vagas remotas, pela escassez de vagas adequadas. Tenho disponibilidade de deslocamento para viagens, contando que a frequência seja razoável.
Sou auto-didata, meu conhecimento não está certificado, mas armazenado no [meu perfil do Github](https://github.com/cleberson-dev) em forma de projetos pessoais. Todo conhecimento foi adquirido através das documentações oficiais das tecnologias, além de blogs, artigos, conferências, videoaulas, repositórios em produção, etc...

## Especialidades

- HTML5/CSS3 
- Bootstrap
- SASS
- JavaScript (ES6+)
- Git
- React.js
- Redux e Recoil
- Reactstrap e Material UI
- Styled Components
- REST
- Jest
- Typescript
- GraphQL (+ Apollo)
- Gatsby.js
- Node.js (+ Express.js)
- Docker
- React Native
- Inglês (Intermediário para Leitura e Escuta | Razoável para fala)

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x] Freela

## Contato

https://www.linkedin.com/in/clebersondev/

## Site

https://clebersondev.netlify.app

**Comment by keviocastro** [comment]
@cleberson-dev  sou de Goiânia e estou com 4 vagas para trabalho home office. Contratação imediata. Podemos fazer uma call pra eu te explicar melhor? Me envie um email por favor keviocastro@gmail.com ou também pode me ligar 62 996026753

**Comment by cleberson-dev** [comment]
> Você ainda está disponível para contratação? Essa issue foi marcada como inativa por não ter nenhuma atividade recente, caso não haja nenhuma nova atividade a mesma será fechada nos próximos 7 dias. Obrigado!

estou ainda disponível para contratação!
