### ISSUE TITLE
[São Paulo/SP] Paulo Marques Vieira

### ISSUE THREAD

**Issue by marquespv** [react-brasil/me-contrata#73]
## Nome completo

Paulo Marques Vieira. 

## Localidade

São Paulo / SP. 

## Apresentação

Graduado em Biologia e Farmácia, graduando em Sistemas de Informação, entusiasta de tecnologia, desenvolvedor de software e soluções em SI. Conhecimentos em ciência de dados e inteligência artificial, modelagem molecular, bioinformática.

## Outras Informações

Conhecimentos em genética e biologia molecular, modelagem computacional, aplicações ambientais (sensoriamento remoto) e modelagem farmacêutica in silico. 

## Especialidades

- JavaScript
- React
- React Native
- R
- Perl
- Python
- ReactJS
- Java
- Delphi
- Scripts Bash
- PHP

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [x] > 5 anos

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/paulo-vieira-5a2b97185/

**Comment by keviocastro** [comment]
@marquespv sou de Goiânia e estou com 4 vagas para trabalho home office. Contratação imediata. Podemos fazer uma call pra eu te explicar melhor? Me envie um email por favor keviocastro@gmail.com ou também pode me ligar 62 996026753
