### ISSUE TITLE
[Barretos/SP] Victor Hugo Malheiro

### ISSUE THREAD

**Issue by VictorhMalheiro** [react-brasil/me-contrata#74]
## Nome completo

Victor Hugo Malheiro.

## Localidade

Barretos / São Paulo.

## Apresentação

Sou desenvolvedor front-end, tenho formação técnica pelo Instituto Federal de São Paulo (IFSP), atualmente estou cursando Sistemas de Informação, sempre fui apaixonado por criar e desenvolver com o diferencial do design que é uma área que tenho experiência de longa data criando interfaces com grande usabilidade, sou desenvolvedor React, React Native e NodeJS, passei pelo incrível treinamento da Rocketseat 🚀, e após isso fui chamado para ministrar um mini-curso no IFSP onde estudei, sou uma pessoa que adora ensinar outras pessoas e também aprender com elas, gosto de estar sempre em busca de me aperfeiçoar cada vez mais. Tenho por preferência o desenvolvimento Mobile com React Native, também tenho experiência com o desenvolvimento de API's em AdonisJS.

## Outras Informações

Procurando uma vaga remoto ou em minha região, sou muito interessado em resolver problemas e ajudar outras pessoas!
- Disponível para viagens
- Bootcamp GoStack | Rocketseat
- Inglês intermediário

## Especialidades

- NodeJS
- JavaScript
- React Native
- Redux
- React
- AdonisJS
- SQL
- Postgres

## Tempo de experiência em TI (Não necessariamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/victormalheiro

**Comment by keviocastro** [comment]
@VictorhMalheiro sou de Goiânia e estou com 4 vagas para trabalho home office. Contratação imediata. Podemos fazer uma call pra eu te explicar melhor? Me envie um email por favor keviocastro@gmail.com ou também pode me ligar 62 996026753
