### ISSUE TITLE
[Arroio do Sal/RS] Bruno César Angst

### ISSUE THREAD

**Issue by BrunoCesarAngst** [react-brasil/me-contrata#78]
## Nome completo

Bruno César Angst

## Localidade

Arroio do Sal - Rio Grande do Sul

## Apresentação

Sou estudante de análise e desenvolvimento de sistema, cursando o terceiro semestre, estou em busca de desafios, colocando em prática, tudo que aprendi até agora.
    Tenho me focado em tecnologias de front-end, back-end e mobile com a stack do JavaScript.

## Outras Informações

Desenvolvedor de front-end · Desenvolvedor de back end · Desenvolvedor de aplicativos móveis · Desenvolvedor Javascript

## Especialidades

  - Node.js
  - React.js
  - React -Native
  - Aplicativos móveis
  - Web Design Responsivo
  - Programação orientada a objetos (POO)
  - Modelagem de dados

Ferramentas e tecnologias
  - HTML  
  - JavaScript
  - CSS
  - Python
  - Linux
  - Docker
  - C (linguagem de programação)
  - Git
  - HTML5
  - SQL
  - NoSQL
  - GitHub
  - PostgreSQL
  - MySQL
  - MongoDB
  - CodeIgniter
  - Bootstrap
  - PL/SQL
  - SQLite
  - PHP

Outras competências
  - Full Stack
  - Express.js
  - Desenvolvimento de back-end
  - Flutter
  - Dart
  - Responsividade
  - Modelagem orientada a objetos
  - Modelagem de banco de dados
  - MySQLi

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [ ] < 1 ano
- [ ] > 1 ano
- [x] > 2 anos
- [ ] > 5 anos

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/brunocesarangst/

## Site

https://www.trabalhocomodev.com/

**Comment by nic** [comment]
Opa Bruno, não deixa de preencher os campos no corpo da `issue`. 
Só clicar em editar:
![Captura de Tela 2020-09-09 às 12 02 40](https://user-images.githubusercontent.com/66042/92616266-66ae4500-f294-11ea-939d-6f0f65af1d3b.png)


Boa sorte! :)
