### ISSUE TITLE
[Remoto] Freelancer frontend

### ISSUE THREAD

**Issue by geovanasilva** [react-brasil/me-contrata#85]
# Nome Completo

Geovana dos Santos Silva

# Localidade

São Paulo 

# Apresentação

Graduada em Análise e Desenvolvimento de Sistemas pela FATEC de Praia Grande. Apaixonada por desenvolvimento frontend mas sempre estudando coisas novas, sou movida por desafios então nesse momento me encontro disponível para possíveis trabalhos como freelancer. Como desenvolvedora tenho experiência com React, Redux, Material UI, testes unitários com Jest e Enzyme/Jest e Test Library e ultimamente estudando/trabalhando com Next e Typescript.

# Outras informações 

- Exam 480: Programming in HTML5 with JavaScript and CSS3 (Microsoft)
- Engenharia de Usabilidade pra Sistemas Web (USP)

# Especialidades

- HTML5
- CSS3
- Javascript
- React
- Redux
- Next
- Typescript
- Jest
- Enzyme
- Test library
- Styled components
- SASS
- Git
- Scrum

# Idiomas

Inglês (Intermediário)

# Experiência

- 2/3 anos
- Junior/pleno

# Disponibilidade

- Freelancer
- Meio período 
- Remoto

# Site (em construção)

https://geovanasilva.dev/

**Comment by jgcmarins** [comment]
Oi @geovanasilva,

Muito legal seu currículo!
Dá uma olhada nesta [vaga](https://github.com/react-brasil/vagas/issues/1009) da @sallve.
Qualquer dúvida, pode me procurar no Slack do React Brasil!

**Comment by alexssandrog** [comment]
Olá @geovanasilva , está em busca de trabalho ainda? Se sim, veja essa [vaga](https://github.com/react-brasil/vagas/issues/1349) da nossa empresa
