### ISSUE TITLE
[Rio de Janeiro/RJ] Rodrigo Antas - React, React Native & NodeJS

### ISSUE THREAD

**Issue by rodrigoantas** [react-brasil/me-contrata#90]
## Nome completo

Rodrigo Antas

## Localidade

Rio de Janeiro - RJ

## Apresentação

Sou um desenvolvedor e trabalho com React, NodeJS & React Native. Moro atualmente no Rio de Janeiro, mas pronto pra qualquer desafio. Por incrível que pareça, antes de me tornar desenvolvedor, fiz faculdade de Psicologia na Universidade do Estado do Rio de Janeiro (UERJ). Depois de um tempo trabalhando no campo da saúde, com publicações de livros e estágios em hospitais psiquiátricos, descobri minha paixão por tecnologia. Com muito esforço, determinação e foco migrei totalmente para a área de tecnologia e estudei o ecossistema Javascript, onde depois de aprender a linguagem pura, me aprimorei em React, React Native, NodeJS e Typescript. Também já trabalhei com Gatsby e NextJS, e vi um pouco de PostgresSQL e MongoDB.

## Especialidades

- JavaScript
- React
- React Native
- NodeJS
- PostgresSQL
- MongoDB
- Dcoker
- Jest
- Git

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [x] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/rodrigo-antas/

## Site

https://github.com/rodrigoantas

**Comment by erickne** [comment]
Olá Rodrigo.

Dê uma olhada na nossa [vaga react](https://link.rockapps.com.br/vaga-dev-react).

Abraços e boa sorte!
