### ISSUE TITLE
[Piedade/SP] Artur Almeida

### ISSUE THREAD

**Issue by zhyph** [react-brasil/me-contrata#91]
## Nome completo

Artur Almeida Junior

## Localidade

Piedade/SP

## Apresentação

Estou estudando cursando Analise e desenvolvimento de sistemas na Anhanguera, estou aprendendo React, JS, C++ e tenho conhecimento prévio de algumas linguagens como Python, PHP, C, Java, porém nenhuma experiência em mercado de trabalho.

## Outras Informações

Atualmente estou 100% disponível e estou disposto a aprender.

## Especialidades

React
WEB(HTML, CSS, JavaScript)
C++

## Tempo de experiência em TI (Não necessáriamente Front-end/React)

- [x] < 1 ano
- [ ] > 1 ano
- [ ] > 2 anos
- [ ] > 5 anos

## Nível

- [x] Estágio
- [ ] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado (Dependendo do local)

## Contato

htps://www.linkedin.com/in/artur-almeida-61ab6a1b4/
E-mail: artur.almeida1@outlook.com

## Site

https://github.com/zhyph

**Comment by kinhu13** [comment]
Artur,
Boa noite.

Favor informar uma contato.

**Comment by zhyph** [comment]
> 
> 
> Artur,
> Boa noite.
> 
> Favor informar uma contato.

Feito, muito obrigado!
